#pragma once

#define ICON_FA_PLAY "\xef\x81\x8b"
#define ICON_FA_PAUSE "\xef\x81\x8c"
#define ICON_FA_STOP "\xef\x81\x8d"
#define ICON_FA_PLUS "\xef\x81\xa7"
#define ICON_FA_TRASH "\xef\x87\xb8"
#define ICON_FA_FOLDER "\xef\x81\xbb"
#define ICON_FA_FILE "\xef\x85\x9b"
#define ICON_FA_CAMERA "\xef\x80\xb0"
#define ICON_FA_VOLUME_HIGH "\xef\x80\xa8"
#define ICON_FA_GEAR "\xef\x80\x93"
#define ICON_FA_PAINT_BRUSH "\xef\x87\xbc"
#define ICON_FA_ERASER "\xef\x84\xad"
#define ICON_FA_CUBES "\xef\x86\xb3"
#define ICON_FA_CUBE "\xef\x86\xb2"
#define ICON_FA_IMAGE "\xef\x80\xbe"
#define ICON_FA_MAP "\xef\x89\xb9"
#define ICON_FA_FILM "\xef\x80\x88"
#define ICON_FA_SAVE "\xef\x83\x87"
